services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']

  App\Service\AuthenticationService:
    arguments:
      $tokenTtl: '%env(int:JWT_EXPIRATION)%'

  App\Controller\Auth\AuthController:
    arguments:
      $googleClientId: '%env(GOOGLE_CLIENT_ID)%'

  App\Service\MailService:
    arguments:
      $frontendUrl: '%env(FRONTEND_URL)%'
      $adminEmail: '%env(ADMIN_EMAIL)%'

  App\Service\FileUploadService:
    arguments:
      $projectDir: '%kernel.project_dir%'

  App\Service\Chatbot\TranslationService:
    arguments:
      $email: '%env(MYMEMORY_EMAIL)%'

  App\Service\Ai\GroqClientService:
    arguments:
      $apiKey: '%env(GROQ_API_KEY)%'
      $model: '%env(GROQ_MODEL)%'

  App\Service\Chatbot\ChatbotService:
    arguments:
      $siteName: '%env(APP_NAME)%'

  Database\Seeders\:
    resource: '../database/seeders/'
    tags: ['doctrine.fixture.orm']
